load('student.rb')
first_guy = Student.new(lastName: "Бекеров", name: "Алиссон", patronymic: "Бразильевич")
second_guy = Student.new(lastName: "Трентов", name: "Саша-Арнольд", patronymic: "Англиевич")
third_guy = Student.new(lastName: "Гомезов", name: "Джо", patronymic: "Англиевич")
fourth_guy = Student.new(lastName: "Вандайков", name: "Вирджил", patronymic: "Голандович")
fifth_guy = Student.new(lastName: "Робертсонов", name: "Эндрю", patronymic:"Скотландович")
sixth_guy = Student.new(lastName: "Нетфамилиев", name: "Фабиньо", patronymic: "Бразильевич")
seventh_guy = Student.new(lastName: "Хендерсонов", name: "Джордан", patronymic: "Англиевич")
eighth_guy = Student.new(lastName: "Милнеров", name: "Джеймс", patronymic: "Англиевич")
nineth_guy = Student.new(lastName:"Мохамедов", name: "Салах", patronymic: "Египтович")
tenth_guy = Student.new(lastName: "Нуньезов", name: "Дарвин", patronymic: "Уругваевич")
eleventh_guy = Student.new(lastName:"Гакпоев", name: "Коди", patronymic: "Голандович")
puts "#{eleventh_guy.to_s}, #{tenth_guy.to_s}, #{nineth_guy.to_s}, #{eighth_guy.to_s}, #{seventh_guy.to_s}, #{sixth_guy.to_s}, #{fifth_guy.to_s}, #{fourth_guy.to_s}, #{third_guy.to_s}, #{second_guy.to_s}, #{first_guy.to_s}"
